name: Build Syncthing
permissions:
  contents: read
  issues: read
  pull-requests: read
env:
  GO_VERSION: ~1.26.0
  GOMIPS: softfloat
  GOARM: '6'
  LOGGER_DISCARD: '1'
  BUILD_USER: builder
  BUILD_HOST: github.syncthing.net
  TAGS: sqlite_omit_load_extension sqlite_dbstat
  TAGS_LINUX: sqlite_omit_load_extension sqlite_dbstat netgo osusergo
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
jobs:
  facts:
    name: Gather common facts
    runs-on: self-hosted
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      release-kind: ${{ steps.get-version.outputs.release-kind }}
      release-generation: ${{ steps.get-version.outputs.release-generation }}
      go-version: ${{ steps.get-go.outputs.go-version }}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false
        check-latest: true
    - name: Get Syncthing version
      id: get-version
      run: |
        version=$(go run build.go version)
        echo "version=$version" >> "$GITHUB_OUTPUT"
        echo "Version: $version"

        kind=stable
        if [[ $version == *-rc.[0-9] || $version == *-rc.[0-9][0-9] ]] ; then
          kind=candidate
        elif [[ $version == *-* ]] ; then
          kind=nightly
        fi
        echo "release-kind=$kind" >> "$GITHUB_OUTPUT"
        echo "Release kind: $kind"

        generation=v1
        if [[ $version == v2.* ]] ; then
          generation=v2
        fi
        echo "release-generation=$generation" >> "$GITHUB_OUTPUT"
        echo "Release generation: $generation"
    - name: Get Go version
      id: get-go
      run: |
        go version
        echo "go-version=$(go version | sed 's#^.*go##;s# .*##')" >> $GITHUB_OUTPUT
    timeout-minutes: 6
  build-test:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        runner:
        - windows-latest
        go:
        - ~1.25.0
    runs-on: self-hosted
    steps:
    - name: Set git to use LF
      if: matrix.runner == 'windows-latest'
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}
        cache: true
        check-latest: true
    - name: Build
      run: |
        go run build.go
    - name: Install go-test-json-to-loki
      run: |
        go install calmh.dev/go-test-json-to-loki@latest
    - name: Test
      run: |
        go version
        go run build.go test | go-test-json-to-loki
      env:
        GOFLAGS: -json
        LOKI_URL: ${{ secrets.LOKI_URL }}
        LOKI_USER: ${{ secrets.LOKI_USER }}
        LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
        LOKI_LABELS: go=${{ matrix.go }},runner=${{ matrix.runner }},repo=${{ github.repository
          }},ref=${{ github.ref }}
        CGO_ENABLED: '1'
    timeout-minutes: 6
  basics:
    name: Basic checks passed
    runs-on: self-hosted
    needs:
    - build-test
    - package-linux
    - package-illumos
    - package-cross
    - package-source
    - package-debian
    - package-windows
    - govulncheck
    - golangci
    - meta
    steps:
    - uses: actions/checkout@v5
    timeout-minutes: 6
    if: ${{ !cancelled() && (!cancelled() && (!cancelled())) }}
  package-windows:
    name: Package for Windows
    runs-on: self-hosted
    needs:
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      RELEASE_KIND: ${{ needs.facts.outputs.release-kind }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ needs.facts.outputs.go-version }}
        cache: false
    - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ needs.facts.outputs.go-version }}-package-windows-${{
          hashFiles('go.sum') }}
    - name: Install dependencies
      run: |
        go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@v1.4.0
    - name: Create packages
      run: |
        for tgt in syncthing stdiscosrv strelaysrv ; do
          go run build.go -tags "${{env.TAGS}}" -goos windows -goarch amd64 -cc "zig cc -target x86_64-windows" zip $tgt
          go run build.go -tags "${{env.TAGS}}" -goos windows -goarch 386 -cc "zig cc -target x86-windows" zip $tgt
          go run build.go -tags "${{env.TAGS}}" -goos windows -goarch arm64 -cc "zig cc -target aarch64-windows" zip $tgt
          # go run build.go -tags "${{env.TAGS}}" -goos windows -goarch arm -cc "zig cc -target thumb-windows" zip $tgt # fails with linker errors
        done
      env:
        CGO_ENABLED: '1'
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-packages-windows
        path: '*.zip'
    timeout-minutes: 6
    if: ${{ !cancelled() && (!cancelled() && (!cancelled())) }}
  package-linux:
    name: Package for Linux (${{ matrix.group }})
    runs-on: self-hosted
    needs:
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      RELEASE_KIND: ${{ needs.facts.outputs.release-kind }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ needs.facts.outputs.go-version }}
        cache: false
    - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ needs.facts.outputs.go-version }}-package-linux-${{
          matrix.group }}-${{ hashFiles('go.sum') }}
    - name: Install extra packages
      if: matrix.extra-packages != ''
      run: sudo apt-get install -y ${{ matrix.extra-packages }}
    - name: Create packages
      run: |
        echo "$TARGETS" | while read -r arch cc; do
          [ -z "$arch" ] && continue
          for tgt in syncthing stdiscosrv strelaysrv ; do
            go run build.go -tags "${{env.TAGS_LINUX}}" -goos linux -goarch "$arch" -cc "$cc" tar "$tgt"
          done
        done
      env:
        CGO_ENABLED: '1'
        EXTRA_LDFLAGS: -linkmode=external -extldflags=-static
        TARGETS: ${{ matrix.targets }}
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-linux-${{ matrix.group }}
        path: |
          *.tar.gz
          compat.json
    timeout-minutes: 6
    if: ${{ !cancelled() && (!cancelled() && (!cancelled())) }}
  package-illumos:
    runs-on: self-hosted
    name: Package for illumos
    needs:
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      GO_VERSION: ${{ needs.facts.outputs.go-version }}
    steps:
    - uses: actions/checkout@v5
    - name: Build syncthing in OmniOS VM
      uses: vmactions/omnios-vm@68da93c6d9812b29fc90c5b5141b093f84a590fb
      with:
        envs: VERSION GO_VERSION CGO_ENABLED
        usesh: true
        prepare: |
          pkg install developer/gcc14 web/curl archiver/gnu-tar
        run: |
          curl -L "https://go.dev/dl/go$GO_VERSION.illumos-amd64.tar.gz" | gtar xzf -
          export PATH="$GITHUB_WORKSPACE/go/bin:$PATH"
          go version
          for tgt in syncthing stdiscosrv strelaysrv ; do
            go run build.go -tags "${{env.TAGS}}" tar "$tgt"
          done
      env:
        CGO_ENABLED: '1'
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-illumos
        path: '*.tar.gz'
    timeout-minutes: 6
    if: ${{ !cancelled() && (!cancelled() && (!cancelled())) }}
  package-cross:
    name: Package cross compiled
    runs-on: self-hosted
    needs:
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      RELEASE_KIND: ${{ needs.facts.outputs.release-kind }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ needs.facts.outputs.go-version }}
        cache: false
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ needs.facts.outputs.go-version }}-cross-${{ hashFiles('go.sum')
          }}
    - name: Create packages
      run: |
        platforms=$(go tool dist list \
          | grep -v aix/ppc64 \
          | grep -v android/ \
          | grep -v darwin/ \
          | grep -v illumos/ \
          | grep -v ios/ \
          | grep -v js/ \
          | grep -v linux/ \
          | grep -v nacl/ \
          | grep -v plan9/ \
          | grep -v windows/ \
          | grep -v /wasm \
        )

        # Build for each platform with errors silenced, because we expect
        # some oddball platforms to fail. This avoids a bunch of errors in
        # the GitHub Actions output, instead summarizing each build
        # failure as a warning.
        for plat in $platforms; do
          goos="${plat%/*}"
          goarch="${plat#*/}"
          echo "::group ::$plat"
          for tgt in syncthing stdiscosrv strelaysrv ; do
            if ! go run build.go -goos "$goos" -goarch "$goarch" tar "$tgt" ; then
              echo "::warning ::Failed to build $tgt for $plat"
            fi
          done
          echo "::endgroup::"
        done
      env:
        CGO_ENABLED: '0'
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-other
        path: '*.tar.gz'
    timeout-minutes: 6
    if: ${{ !cancelled() && (!cancelled() && (!cancelled())) }}
  package-source:
    name: Package source code
    runs-on: self-hosted
    needs:
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      RELEASE_KIND: ${{ needs.facts.outputs.release-kind }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ needs.facts.outputs.go-version }}
        cache: false
    - name: Package source
      run: |
        echo "$VERSION" > RELEASE

        go mod vendor
        go run build.go assets

        cd ..

        tar c -z -f "syncthing-source-$VERSION.tar.gz" \
          --exclude .git \
          syncthing

        mv "syncthing-source-$VERSION.tar.gz" syncthing
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-source
        path: syncthing-source-*.tar.gz
    timeout-minutes: 6
    if: ${{ !cancelled() && (!cancelled() && (!cancelled())) }}
  sign-for-upgrade:
    name: Sign for upgrade
    if: ${{ !cancelled() && (!cancelled() && (!cancelled() && (true && (github.event_name
      == 'push' || github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/release-nightly'
      || startsWith(github.ref, 'refs/tags/v'))))) }}
    needs:
    - package-linux
    - package-illumos
    - package-cross
    - package-source
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      RELEASE_KIND: ${{ needs.facts.outputs.release-kind }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v5
    - uses: actions/checkout@v5
      with:
        repository: syncthing/release-tools
        path: tools
    - name: Download artifacts
      uses: actions/download-artifact@v7
      with:
        pattern: packages-*
        path: packages
        merge-multiple: true
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ needs.facts.outputs.go-version }}
        cache: false
    - name: Install signing tool
      run: |
        go install ./cmd/dev/stsigtool
    - name: Sign archives
      run: |
        export PRIVATE_KEY="$RUNNER_TEMP/privkey.pem"
        export PATH="$PATH:$(go env GOPATH)/bin"
        echo "$STSIGTOOL_PRIVATE_KEY" | base64 -d > "$PRIVATE_KEY"
        pushd packages
        "$GITHUB_WORKSPACE/tools/sign-only"
        rm -f "$PRIVATE_KEY"
      env:
        STSIGTOOL_PRIVATE_KEY: ${{ secrets.STSIGTOOL_PRIVATE_KEY }}
    - name: Create shasum files
      run: |
        pushd packages
        files=(*.tar.gz *.zip)
        sha1sum "${files[@]}" > sha1sum.txt
        sha256sum "${files[@]}" > sha256sum.txt
        popd
    - name: Sign shasum files
      uses: docker://ghcr.io/kastelo/ezapt:latest
      with:
        args: sign packages/sha1sum.txt packages/sha256sum.txt
      env:
        EZAPT_KEYRING_BASE64: ${{ secrets.APT_GPG_KEYRING_BASE64 }}
    - name: Sign source
      uses: docker://ghcr.io/kastelo/ezapt:latest
      with:
        args: sign --detach --ascii packages/syncthing-source-${{ env.VERSION }}.tar.gz
      env:
        EZAPT_KEYRING_BASE64: ${{ secrets.APT_GPG_KEYRING_BASE64 }}
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-signed
        path: |
          packages/*.tar.gz
          packages/*.zip
          packages/*.asc
          packages/*.json
    timeout-minutes: 6
  package-debian:
    name: Package for Debian
    runs-on: self-hosted
    needs:
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      RELEASE_KIND: ${{ needs.facts.outputs.release-kind }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ needs.facts.outputs.go-version }}
        cache: false
    - uses: ruby/setup-ruby@eab2afb99481ca09a4e91171a8e0aee0e89bfedd
      with:
        ruby-version: '3.0'
    - name: Install fpm
      run: |
        gem install fpm
    - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ needs.facts.outputs.go-version }}-debian-${{
          hashFiles('go.sum') }}
    - name: Package for Debian (CGO)
      run: |
        for tgt in syncthing stdiscosrv strelaysrv ; do
          go run build.go -no-upgrade -installsuffix=no-upgrade -tags "${{env.TAGS_LINUX}}" -goos linux -goarch amd64 -cc "zig cc -target x86_64-linux-musl" deb "$tgt"
          go run build.go -no-upgrade -installsuffix=no-upgrade -tags "${{env.TAGS_LINUX}}" -goos linux -goarch armel -cc "zig cc -target arm-linux-musleabi -mcpu=arm1136j_s" deb "$tgt"
          go run build.go -no-upgrade -installsuffix=no-upgrade -tags "${{env.TAGS_LINUX}}" -goos linux -goarch armhf -cc "zig cc -target arm-linux-musleabi -mcpu=arm1136j_s" deb "$tgt"
          go run build.go -no-upgrade -installsuffix=no-upgrade -tags "${{env.TAGS_LINUX}}" -goos linux -goarch arm64 -cc "zig cc -target aarch64-linux-musl" deb "$tgt"
        done
      env:
        BUILD_USER: debian
        CGO_ENABLED: '1'
        EXTRA_LDFLAGS: -linkmode=external -extldflags=-static
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debian-packages
        path: '*.deb'
    timeout-minutes: 6
    if: ${{ !cancelled() && (!cancelled() && (!cancelled())) }}
  publish-nightly:
    name: Publish nightly build
    if: ${{ !cancelled() && (!cancelled() && (!cancelled() && (true && (github.event_name
      == 'push' || github.event_name == 'workflow_dispatch') && startsWith(github.ref,
      'refs/heads/release-nightly')))) }}
    needs:
    - sign-for-upgrade
    - facts
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v5
      with:
        repository: syncthing/release-tools
        path: tools
    - name: Download artifacts
      uses: actions/download-artifact@v7
      with:
        name: packages-signed
        path: packages
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ needs.facts.outputs.go-version }}
        cache: false
    - name: Create release json
      run: |
        cd packages
        "$GITHUB_WORKSPACE/tools/generate-release-json" "$BASE_URL" > nightly.json
      env:
        BASE_URL: ${{ secrets.NIGHTLY_BASE_URL }}
    - name: Push artifacts
      uses: docker://docker.io/rclone/rclone:latest
      env:
        RCLONE_CONFIG_OBJSTORE_TYPE: s3
        RCLONE_CONFIG_OBJSTORE_PROVIDER: ${{ secrets.S3_PROVIDER }}
        RCLONE_CONFIG_OBJSTORE_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        RCLONE_CONFIG_OBJSTORE_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY
          }}
        RCLONE_CONFIG_OBJSTORE_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        RCLONE_CONFIG_OBJSTORE_REGION: ${{ secrets.S3_REGION }}
        RCLONE_CONFIG_OBJSTORE_ACL: public-read
      with:
        args: sync -v --no-update-modtime packages objstore:nightly
    timeout-minutes: 6
  publish-release-files:
    name: Publish release files
    if: ${{ !cancelled() && (!cancelled() && (!cancelled() && (true && (github.event_name
      == 'push' || github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/release'
      || startsWith(github.ref, 'refs/tags/v'))))) }}
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    needs:
    - sign-for-upgrade
    - package-debian
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      RELEASE_KIND: ${{ needs.facts.outputs.release-kind }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - name: Download signed packages
      uses: actions/download-artifact@v7
      with:
        name: packages-signed
        path: packages
    - name: Download debian packages
      uses: actions/download-artifact@v7
      with:
        name: debian-packages
        path: packages
    - name: Create GitHub build provenance attestations
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: packages/*
    - name: Push to object store (${{ env.VERSION }})
      uses: docker://docker.io/rclone/rclone:latest
      env:
        RCLONE_CONFIG_OBJSTORE_TYPE: s3
        RCLONE_CONFIG_OBJSTORE_PROVIDER: ${{ secrets.S3_PROVIDER }}
        RCLONE_CONFIG_OBJSTORE_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        RCLONE_CONFIG_OBJSTORE_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY
          }}
        RCLONE_CONFIG_OBJSTORE_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        RCLONE_CONFIG_OBJSTORE_REGION: ${{ secrets.S3_REGION }}
        RCLONE_CONFIG_OBJSTORE_ACL: public-read
      with:
        args: sync -v --no-update-modtime packages objstore:release/${{ env.VERSION
          }}
    - name: Push to object store (latest)
      uses: docker://docker.io/rclone/rclone:latest
      env:
        RCLONE_CONFIG_OBJSTORE_TYPE: s3
        RCLONE_CONFIG_OBJSTORE_PROVIDER: ${{ secrets.S3_PROVIDER }}
        RCLONE_CONFIG_OBJSTORE_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        RCLONE_CONFIG_OBJSTORE_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY
          }}
        RCLONE_CONFIG_OBJSTORE_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        RCLONE_CONFIG_OBJSTORE_REGION: ${{ secrets.S3_REGION }}
        RCLONE_CONFIG_OBJSTORE_ACL: public-read
      with:
        args: sync -v --no-update-modtime objstore:release/${{ env.VERSION }} objstore:release/latest
    - name: Create GitHub releases and push binaries
      run: |
        maybePrerelease=""
        if [[ $VERSION == *-* ]]; then
          maybePrerelease="--prerelease"
        fi
        export GH_PROMPT_DISABLED=1
        if ! gh release view --json name "$VERSION" >/dev/null 2>&1 ; then
          gh release create "$VERSION" \
            $maybePrerelease \
            --draft \
            --title "$VERSION" \
            --notes-from-tag
        fi

        gh release upload --clobber "$VERSION" \
          packages/*.asc packages/*.json \
          packages/syncthing-*.tar.gz \
          packages/syncthing-*.zip \
          packages/syncthing_*.deb
        gh release edit "$VERSION" --draft=false

        PKGS=$(pwd)/packages
        cd /tmp # gh will not release for repo x while inside repo y
        for repo in relaysrv discosrv ; do
          export GH_REPO="syncthing/$repo"
          if ! gh release view --json name "$VERSION" >/dev/null 2>&1 ; then
            gh release create "$VERSION" \
              $maybePrerelease \
              --draft \
              --title "$VERSION" \
              --notes "https://github.com/syncthing/syncthing/releases/tag/$VERSION"
          fi
          gh release upload --clobber "$VERSION" \
            $PKGS/*.asc \
            $PKGS/*${repo}*
          gh release edit "$VERSION" --draft=false
        done
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    timeout-minutes: 6
  publish-apt:
    name: Publish APT
    if: ${{ !cancelled() && (!cancelled() && (!cancelled() && (true && (github.event_name
      == 'push' || github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/release-nightly'
      || startsWith(github.ref, 'refs/tags/v'))))) }}
    needs:
    - package-debian
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      RELEASE_KIND: ${{ needs.facts.outputs.release-kind }}
      RELEASE_GENERATION: ${{ needs.facts.outputs.release-generation }}
    runs-on: self-hosted
    steps:
    - name: Download packages
      uses: actions/download-artifact@v7
      with:
        name: debian-packages
        path: packages
    - name: Pull archive
      uses: docker://docker.io/rclone/rclone:latest
      env:
        RCLONE_CONFIG_OBJSTORE_TYPE: s3
        RCLONE_CONFIG_OBJSTORE_PROVIDER: ${{ secrets.S3_PROVIDER }}
        RCLONE_CONFIG_OBJSTORE_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        RCLONE_CONFIG_OBJSTORE_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY
          }}
        RCLONE_CONFIG_OBJSTORE_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        RCLONE_CONFIG_OBJSTORE_REGION: ${{ secrets.S3_REGION }}
        RCLONE_CONFIG_OBJSTORE_ACL: public-read
      with:
        args: sync objstore:apt apt
    - name: Prepare packages
      run: |
        sudo chown -R $(id -u) apt/pool
        mv -n packages/*.deb apt/pool
    - name: Update archive
      uses: docker://ghcr.io/kastelo/ezapt:latest
      with:
        args: publish --root apt
      env:
        EZAPT_KEYRING_BASE64: ${{ secrets.APT_GPG_KEYRING_BASE64 }}
    - name: Push archive
      uses: docker://docker.io/rclone/rclone:latest
      env:
        RCLONE_CONFIG_OBJSTORE_TYPE: s3
        RCLONE_CONFIG_OBJSTORE_PROVIDER: ${{ secrets.S3_PROVIDER }}
        RCLONE_CONFIG_OBJSTORE_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        RCLONE_CONFIG_OBJSTORE_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY
          }}
        RCLONE_CONFIG_OBJSTORE_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        RCLONE_CONFIG_OBJSTORE_REGION: ${{ secrets.S3_REGION }}
        RCLONE_CONFIG_OBJSTORE_ACL: public-read
      with:
        args: sync -v --no-update-modtime apt objstore:apt
    timeout-minutes: 6
  docker-ghcr:
    name: Build and push Docker images (GHCR)
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    needs:
    - facts
    env:
      VERSION: ${{ needs.facts.outputs.version }}
      RELEASE_KIND: ${{ needs.facts.outputs.release-kind }}
    strategy:
      fail-fast: false
      matrix:
        pkg:
        - syncthing
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ needs.facts.outputs.go-version }}
        cache: false
    - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ needs.facts.outputs.go-version }}-docker-${{
          matrix.pkg }}-${{ hashFiles('go.sum') }}
    - name: Build binaries (CGO)
      run: |
        mkdir bin

        # amd64
        go run build.go -goos linux -goarch amd64 -tags "${{env.TAGS_LINUX}}" -cc "zig cc -target x86_64-linux-musl" -no-upgrade build ${{ matrix.pkg }}
        mv ${{ matrix.pkg }} bin/${{ matrix.pkg }}-linux-amd64

        # arm64
        go run build.go -goos linux -goarch arm64 -tags "${{env.TAGS_LINUX}}" -cc "zig cc -target aarch64-linux-musl" -no-upgrade build ${{ matrix.pkg }}
        mv ${{ matrix.pkg }} bin/${{ matrix.pkg }}-linux-arm64

        # arm
        go run build.go -goos linux -goarch arm -tags "${{env.TAGS_LINUX}}" -cc "zig cc -target arm-linux-musleabi -mcpu=arm1136j_s" -no-upgrade build ${{ matrix.pkg }}
        mv ${{ matrix.pkg }} bin/${{ matrix.pkg }}-linux-arm
      env:
        CGO_ENABLED: '1'
        BUILD_USER: docker
        EXTRA_LDFLAGS: -linkmode=external -extldflags=-static
    - name: Login to GHCR
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
    - name: Set version tags
      run: |
        version=${VERSION#v}
        repo=ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}
        ref="${REF_NAME}"
        ref=${ref//\//-} # slashes to dashes

        # List of tags for ghcr.io
        if [[ $version == @([0-9]|[0-9][0-9]).@([0-9]|[0-9][0-9]).@([0-9]|[0-9][0-9]) ]] ; then
          major=${version%.*.*}
          minor=${version%.*}
          tags=$repo:$version,$repo:$major,$repo:$minor,$repo:latest
        elif [[ $version == *-rc.@([0-9]|[0-9][0-9]) ]] ; then
          tags=$repo:$version,$repo:rc
        elif [[ $ref == "main" ]] ; then
          tags=$repo:edge
        else
          tags=$repo:$ref
        fi

        echo Pushing to $tags
        echo "DOCKER_TAGS=$tags" >> $GITHUB_ENV
      env:
        REF_NAME: ${{github.ref_name}}
    - name: Prepare context dir
      run: |
        mkdir ctx
        mv bin/* script ctx
    - name: Build and push Docker image
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
      with:
        context: ctx
        file: ${{ matrix.dockerfile }}
        platforms: linux/amd64,linux/arm64,linux/arm/7
        tags: ${{ env.DOCKER_TAGS }}
        push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch'
          }}
        labels: |
          org.opencontainers.image.version=${{ env.VERSION }}
          org.opencontainers.image.revision=${{ github.sha }}
    timeout-minutes: 6
    if: ${{ !cancelled() && (!cancelled() && (!cancelled())) }}
  docker-hub:
    name: Sync images to Docker hub
    if: ${{ !cancelled() && (!cancelled() && (!cancelled() && (true && (github.event_name
      == 'push' || github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/main'
      || github.ref == 'refs/heads/release-nightly' || github.ref == 'refs/heads/infrastructure'
      || startsWith(github.ref, 'refs/tags/v'))))) }}
    runs-on: self-hosted
    needs:
    - docker-ghcr
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v5
    - name: Sync images
      uses: docker://docker.io/regclient/regsync:latest
      with:
        args: -c ./.github/regsync.yml once
    timeout-minutes: 6
  govulncheck:
    runs-on: self-hosted
    name: Run govulncheck
    needs:
    - facts
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ needs.facts.outputs.go-version }}
        cache: false
    - name: run govulncheck
      run: |
        go run build.go assets
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
    timeout-minutes: 6
    if: ${{ !cancelled() && (!cancelled() && (!cancelled())) }}
  golangci:
    runs-on: self-hosted
    name: Run golangci-lint
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: stable
    - name: ensure asset generation
      run: go run build.go assets
    - name: golangci-lint
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
      with:
        only-new-issues: true
    timeout-minutes: 6
  meta:
    name: Run meta checks
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: stable
    - run: |
        go run build.go assets
        go test -v ./meta
    timeout-minutes: 6
'on':
  pull_request: null
  push:
    branches-ignore:
    - release
    - release-rc*
  workflow_call: null
  workflow_dispatch: null
